import { SectionIndex } from "@/components/body";
import { Header } from "@/components/header";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [currentPage, SetCurrentPage] = useState("home");

  function handlePage(page) {
    SetCurrentPage(page);
  }

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Home | Camilo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-white flex dark:bg-gray-800 ">
          {<Header handlePage={handlePage} currentPage={currentPage} />}
          {<SectionIndex />}
        </div>
      </main>
    </div>
  );
}
